[package]
name = "libarchive"
version = "0.1.0"
authors = ["Jamie Winsor <jamie@vialstudios.com>"]
license = "MIT"
repository = "https://github.com/reset/libarchive-rust"

[dependencies]
libc = "*"

[dependencies.libarchive3-sys]
git = "https://github.com/reset/libarchive3-sys"
branch = "master"
